### PR TITLE
Some new alarms :)

### PR DESCRIPTION
**Pull request by CryptAlchemy**

### CODE REVIEW

**Comment by CryptAlchemy** [comment]
Anybody home?

**Comment by alecdwm** [comment]
Hey @CryptAlchemy, I'm not a project maintainer but I followed it some years ago.

IIRC, this project has been officially 'unmaintained' for quite some time now.  
Also, even when it was actively maintained, I'm fairly certain the team didn't used to actively look after pull requests to this GitHub repo; they (IIRC) had a 'developers-only' repo from back when the project was using svn which would be pushed here on GitHub when new revisions were ready for the community.

From https://github.com/RafaelDeJongh/cap/wiki

> The future and end of CAP!
> After many years, where lots of talented people came together to make this addon possible, where others supported the addon in their own way. We sadly had to announce the disbandment of the Carter Addon Pack's team on 11/12/2015.
>
> With the disbandment of the team we made a decision to further extend the future of CAP and as a general Stargate addon for Garry's Mod. To make our content publicly available for others to remix, transform or build upon, to make adaptations of the addon or make a complete new Stargate Addon!
>
> This whole addon is from that day licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License. More information can be found on the FAQ Licensing Page.

**Comment by AlexALX** [comment]
Actually we look into pull requests and merge them from time to time into cap, but cap resources bit harder to update on workshop. Anyway adding just 2 sounds files is not really good reason to take time and update it. When there will be more content or also some free time then it might be merged, but this can happen not soon.

**Comment by CryptAlchemy** [comment]
Aww man. Was hoping to get some good sounds in xD. Looks like I have to code something now :P

**Comment by CryptAlchemy** [comment]
Come on guys, it doesn't take 10 years to update a Github...

**Comment by RafaelDeJongh** [comment]
Like Alex mentioned before, we're not going to update the cap_resources github/workshop just for two files. If more resource content required to be edited then we will push this together with the rest of the content required in that update.

And I will note again that our team has been disbanded therefore no one really has dedicated time on their hands to actually integrate anything from CAP these days. So it might take a bit longer than what you could expect compared to the earlier times when CAP was being developed.

**Comment by CryptAlchemy** [comment]
I see. I guess I'll just have to develop some new things for CAP xD

**Comment by RafaelDeJongh** [comment]
Feel free to do so ;) any contribution is always welcome!

**Comment by AlexALX** [comment]
Oh why i always forgot to included this into cap... damn another update was just uploaded, but i forgot included this as always...

**Comment by CryptAlchemy** [comment]
Haha

**Comment by cartman300** [comment]
What's wrong with merging this into the main repository and just updating workstop whenever you feel like it? Workshop and git don't have to contain 1:1 code/resources.

**Comment by CryptAlchemy** [comment]
Hooray!

**Comment by AlexALX** [comment]
Just did pushed update to workshop, so now this files are available for everyone.

**Comment by CryptAlchemy** [comment]
Spectacular!

**Pull request merged**
